# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "octy-app"
client_id = "9ff0974b54554e8f77107be0bef2c9d7"
application_url = "https://kiss-fi-also-encounter.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,write_pixels,write_products,write_checkouts,write_orders,write_metaobjects,read_metaobjects,write_discounts,write_price_rules"

[auth]
redirect_urls = [
  "https://kiss-fi-also-encounter.trycloudflare.com/auth/callback",
  "https://kiss-fi-also-encounter.trycloudflare.com/auth/shopify/callback",
  "https://kiss-fi-also-encounter.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "octymart.myshopify.com"
