# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ff0974b54554e8f77107be0bef2c9d7"
name = "octy-app"
application_url = "https://adds-glass-dining-lo.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "octymart.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_metaobjects,write_checkouts,write_discounts,write_metaobjects,write_orders,write_pixels,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://adds-glass-dining-lo.trycloudflare.com/auth/callback",
  "https://adds-glass-dining-lo.trycloudflare.com/auth/shopify/callback",
  "https://adds-glass-dining-lo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
